In [1]:
import numpy as np

In [21]:
f = open("samplenetwork.csv")
line = f.readline()
nline = line.rstrip("\n")
print(nline)

temp = nline.split(",")
print(temp)

f.close()

N,101,1101,1103
['N', '101', '1101', '1103']


In [2]:
data = np.loadtxt("samplenetwork3.csv", delimiter=",", dtype="int32")
print(data)

[[ 101 1101 1103    0    0]
 [ 102 1103 1102 1013    0]
 [ 103 1104 1001 1101    0]
 [ 104 1102 1014 1104 1002]
 [ 201 1201 1013 1203    0]
 [ 202 1203 1202 1019    0]
 [ 203 1204 1003 1201 1014]
 [ 204 1202 1020 1204 1004]
 [ 301 1301 1019 1303    0]
 [ 302 1303 1302    0    0]
 [ 303 1304 1005 1301 1020]
 [ 304 1302 1304 1006    0]
 [ 401 1401 1403 1001    0]
 [ 402 1403 1002 1402 1015]
 [ 403 1404 1007 1401    0]
 [ 404 1402 1016 1404 1008]
 [ 501 1501 1015 1503 1003]
 [ 502 1503 1004 1502 1021]
 [ 503 1504 1009 1501 1016]
 [ 504 1502 1022 1504 1010]
 [ 601 1601 1021 1603 1005]
 [ 602 1603 1006 1602    0]
 [ 603 1604 1011 1601 1022]
 [ 604 1602 1604 1012    0]
 [ 701 1701 1703 1007    0]
 [ 702 1703 1008 1702 1017]
 [ 703 1704 1701    0    0]
 [ 704 1702 1018 1704    0]
 [ 801 1801 1017 1803 1009]
 [ 802 1803 1010 1802 1023]
 [ 803 1804 1801 1018    0]
 [ 804 1802 1024 1804    0]
 [ 901 1901 1023 1903 1011]
 [ 902 1903 1012 1902    0]
 [ 903 1904 1901 1024    0]
 [ 904 1902 1904    

In [3]:
print(data[0,:])

[ 101 1101 1103    0    0]


In [4]:
link = data[data[:,0]>1000,:]
print(link)

[[1101  103  101    0    0]
 [1102  102  104    0    0]
 [1103  101  102    0    0]
 [1104  104  103    0    0]
 [1201  203  201    0    0]
 [1202  202  204    0    0]
 [1203  201  202    0    0]
 [1204  204  203    0    0]
 [1301  303  301    0    0]
 [1302  302  304    0    0]
 [1303  301  302    0    0]
 [1304  304  303    0    0]
 [1401  403  401    0    0]
 [1402  402  404    0    0]
 [1403  401  402    0    0]
 [1404  404  403    0    0]
 [1501  503  501    0    0]
 [1502  502  504    0    0]
 [1503  501  502    0    0]
 [1504  504  503    0    0]
 [1601  603  601    0    0]
 [1602  602  604    0    0]
 [1603  601  602    0    0]
 [1604  604  603    0    0]
 [1701  703  701    0    0]
 [1702  702  704    0    0]
 [1703  701  702    0    0]
 [1704  704  703    0    0]
 [1801  803  801    0    0]
 [1802  802  804    0    0]
 [1803  801  802    0    0]
 [1804  804  803    0    0]
 [1901  903  901    0    0]
 [1902  902  904    0    0]
 [1903  901  902    0    0]
 [1904  904  903    

In [5]:
node = data[data[:,0]<1000,:]
print(node)

[[ 101 1101 1103    0    0]
 [ 102 1103 1102 1013    0]
 [ 103 1104 1001 1101    0]
 [ 104 1102 1014 1104 1002]
 [ 201 1201 1013 1203    0]
 [ 202 1203 1202 1019    0]
 [ 203 1204 1003 1201 1014]
 [ 204 1202 1020 1204 1004]
 [ 301 1301 1019 1303    0]
 [ 302 1303 1302    0    0]
 [ 303 1304 1005 1301 1020]
 [ 304 1302 1304 1006    0]
 [ 401 1401 1403 1001    0]
 [ 402 1403 1002 1402 1015]
 [ 403 1404 1007 1401    0]
 [ 404 1402 1016 1404 1008]
 [ 501 1501 1015 1503 1003]
 [ 502 1503 1004 1502 1021]
 [ 503 1504 1009 1501 1016]
 [ 504 1502 1022 1504 1010]
 [ 601 1601 1021 1603 1005]
 [ 602 1603 1006 1602    0]
 [ 603 1604 1011 1601 1022]
 [ 604 1602 1604 1012    0]
 [ 701 1701 1703 1007    0]
 [ 702 1703 1008 1702 1017]
 [ 703 1704 1701    0    0]
 [ 704 1702 1018 1704    0]
 [ 801 1801 1017 1803 1009]
 [ 802 1803 1010 1802 1023]
 [ 803 1804 1801 1018    0]
 [ 804 1802 1024 1804    0]
 [ 901 1901 1023 1903 1011]
 [ 902 1903 1012 1902    0]
 [ 903 1904 1901 1024    0]
 [ 904 1902 1904    

In [6]:
allnode = node[:,0]
print(allnode)

[101 102 103 104 201 202 203 204 301 302 303 304 401 402 403 404 501 502
 503 504 601 602 603 604 701 702 703 704 801 802 803 804 901 902 903 904]


In [41]:
subjnode = 503
index = np.where(node[:,0]==subjnode)
print(index)
chknode = node[index].ravel()
print(chknode)

(array([18], dtype=int64),)
[ 503 1504 1009 1501 1016]


In [42]:
nextlink = chknode[1:]
print(nextlink)

[1504 1009 1501 1016]


In [43]:
index = np.where(link[:,0]==nextlink[0])
print(index)
chklink = link[index].ravel()
print(chklink)

(array([19], dtype=int64),)
[1504  504  503    0    0]


In [44]:
if chklink[1] == 503:
    pushnode = chklink[2]
else:
    pushnode = chklink[1]
print(pushnode)

504
